title: Suecipes
baseURL: 'https://suecipes.com'
languageCode: 'en-us'
theme: [lugo-master]

relativeURLs: true
params:
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext: ""
  favicon: "/favicon.ico"

  # Site description - used in meta tags and social media cards
  description: "Suecipes - A collection of our favourite recipies simply formatted for easy reading and reference."
  
  # Default social media image (used when a page doesn't have its own image)
  ogimage: "/images/opengraph-img.jpg"
  
  # Publisher logo for structured data
  publisherLogo: "/images/leon-icon-01.svg"
  
  #list items
  datesinlist: false
  authorsinlist: true

  #footer items
  nextprev: false
  taglist: true
  showrss: false

  markup:
  goldmark:
    renderer:
      unsafe: true


  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

summaryLength: 30

outputs:
    home: [HTML, RSS, JSON]
